### ISSUE TITLE
Select/deselect on smartphone not toggling immediately

### ISSUE THREAD

**Issue by AndersWinther-Dahl** [arca-computing/MultipleDatePicker#49] opened 2016-05-03 11:23 UTC
Hi,
Just started using this nice date picker, but having a little issue when using it on a smartphone (touch).
When a selected date is deselected, then it first shows when another day is rouched or touching outside the date picker.

It's the same behavior on the demo page.

Is this intended or do know a work around?

Best regards,
Anders

**Comment by mgohin** [comment] 2016-05-03 11:27
I can reproduce, it's not intended, I'll see what I can do, it's just css I guess

**Comment by mgohin** [comment] 2016-05-03 12:02
It's a hover problem, I'll try to fix it by removing `:hover` in css

**Comment by mgohin** [comment] 2016-05-03 12:15
I can't really fix that without compromises for the desktop version, maybe a pure css solution fits for you using media queries, for example (not tested) :

    @media screen and (max-width: 480px) {
        //override every :hover css for the date picker
        .picker-day.today:hover,
        .picker-day.today.picker-off:hover,
        ... etc {
            background-color: #ffffff;
        }
    }

Let me know ;)

**Comment by AndersWinther-Dahl** [comment] 2016-05-03 12:40
Thanks for your quick response!

I'm not a CSS pro, but your suggestion made me look at the following:
.picker-day:not(.picker-off):not(.picker-empty):hover {
    /* background-color: #c6000b; */
    /* color: #ffffff; */
    cursor: pointer;
}
By removing background-color and color it seems like it's fixed, for both desktop and smartphone.
Can you confirm that I didn't brake something else?

**Comment by mgohin** [comment] 2016-05-03 12:44
It "breaks" nothing but you will not have the hover color on desktop. If it suits you, you can override it in your css ;)

**Comment by mgohin** [comment] 2016-05-03 13:12
Look here : http://getbootstrap.com/css/#grid-media-queries

Here is what I would use, test it and adapt it, I don't have time to test it sorry (I'm at work ;) )

```css
@media screen and (max-width: 768px) {
    .picker-day:not(.picker-off):not(.picker-empty):hover{
        background-color: #fff;
        color: #000;
    }
}

@media screen and (min-width: 768px) and (max-width: 992px) {
    .picker-day:not(.picker-off):not(.picker-empty):hover{
        background-color: #fff;
        color: #000;
    }
}

**Comment by AndersWinther-Dahl** [comment] 2016-05-03 13:19
Thanks! Will try!

**Comment by mgohin** [comment] 2016-05-09 07:12
Is it working ?

**Comment by AndersWinther-Dahl** [comment] 2016-05-09 07:32
I didn't go the media type way, since I believe high resolution devices wouldn't get affected by the fix. So right now I simply removed the hover definition.

**Comment by mgohin** [comment] 2016-05-09 07:33
Alright then, I close the issue.
Let me know if you need something else ;)

**Closed by mgohin** 2016-05-09 07:33 UTC
